export const allumniOffline = [
    {
        "name": "Agustín Verdú",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Technology and Telecommunication Degree",
        "degree": "Technical",
        "related": "no",
        "professional": "Consultant and Engineering of Radiofrequency ",
        "workType": "More than 5 years",
        "workTime": "Master ",
        "previousExt": "Communications and Development of Mobile Services (600h)"
    },
    {
        "name": "Alberto Joaquin Lara Orozco",
        "dob": "21/06/1988",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Chemistry Degree",
        "degree": "Sciences",
        "related": "no",
        "professional": "Laboratory Analyst",
        "workType": "Less than 2 years",
        "workTime": "Autonomous Learning (400h)",
        "previousExt": "Java bases using Eclipse "
    },
    {
        "name": "Alexander Vogl Gómez",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Bachelor and Master Business Administration",
        "degree": "Business",
        "related": "no",
        "professional": "Financial Advisor and Bank Assistant Manager ",
        "workType": "More than 5 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Marti Pi Martin ",
        "dob": "",
        "country": "",
        "program": "Front-end",
        "education": "Business Managment and Administration and international ",
        "degree": "",
        "related": "",
        "professional": "",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Ana Luisa Basso",
        "dob": "",
        "country": "",
        "program": "Data Analystics ",
        "education": "Bachelor in Communication and Master Degree in Economics ",
        "degree": "Business",
        "related": "no",
        "professional": "Digital Project Managment ",
        "workType": "More than 5 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Ana Madera ",
        "dob": "",
        "country": "",
        "program": "Front-end",
        "education": "Audiovisual Communication Degree ",
        "degree": "Humanities",
        "related": "no",
        "professional": "Web Design ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Andrea De Candia",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Bachelor of Arts and Major in Economics and Political Sciences ",
        "degree": "Business",
        "related": "no",
        "professional": "Mutual Fund Accountant ",
        "workType": "More than 2 years",
        "workTime": "No",
        "previousExt": ""
    },
    {
        "name": "Andreu Dorda Fernandez",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Bachelor in Advertising and Public Relations ",
        "degree": "Business",
        "related": "no",
        "professional": "Copywriter and Brand Strategist",
        "workType": "More than 2 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Andrew Padel ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "French Bachelor's Degree ",
        "degree": "Humanities",
        "related": "no",
        "professional": "English Teacher ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Anton Salomin",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Finance and Economics Degree ",
        "degree": "Business",
        "related": "no",
        "professional": "English teacher and translator",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Aoife Byrne ",
        "dob": "",
        "country": "",
        "program": "Data Analystics ",
        "education": "Degree Pure Mathematics ",
        "degree": "Sciences",
        "related": "no",
        "professional": "Project Manager ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Arjen Van Den Heuvel",
        "dob": "",
        "country": "Netherlands ",
        "program": "Data Analystics ",
        "education": "Bachelor's in Science (BSc) Business Administration and Master of Science (MSc)  in Marketing Managment ",
        "degree": "Business",
        "related": "no",
        "professional": "Process specialist and Business Manager ",
        "workType": "More than 5 years",
        "workTime": "No",
        "previousExt": "-"
    },
    {
        "name": "Armin Talic",
        "dob": "",
        "country": "",
        "program": "Data Analystics ",
        "education": "BSc Mechanical Engineering ",
        "degree": "Technical",
        "related": "no",
        "professional": "Mechanical Engineer ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Ashley Cramer ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Managment and French Degree/ Master International Business ",
        "degree": "Business",
        "related": "no",
        "professional": "Online Marketing and Sales Assistant ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Auger Oriol Miquel Estadella",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Computer Engineering (2 Years) ",
        "degree": "Technical",
        "related": "no",
        "professional": "Sound Technician ",
        "workType": "More than 5 years",
        "workTime": "Autonomous Learning (200h)",
        "previousExt": "Practise learning the bases of Ruby using C9 IDE"
    },
    {
        "name": "Barbara Blay",
        "dob": "",
        "country": "",
        "program": "Data Analystics ",
        "education": "Law Degree ",
        "degree": "Law",
        "related": "no",
        "professional": "Sales prediction",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Barthélémy Ghez",
        "dob": "",
        "country": "Paris ",
        "program": "Data Analystics ",
        "education": "MSC in Financial Markets and Investments",
        "degree": "Business",
        "related": "no",
        "professional": "Fund Analyst Assistant ",
        "workType": "More than 2 years",
        "workTime": "No",
        "previousExt": ""
    },
    {
        "name": "Blanca Barón",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "BSc in Business Managment and Administration, also in Economics",
        "degree": "Business",
        "related": "no",
        "professional": "Sales and Business Development",
        "workType": "More than 5 years",
        "workTime": "Online Course ",
        "previousExt": "Learn to code Python"
    },
    {
        "name": "Bryn Gonsalves Williams",
        "dob": "23/08/1988",
        "country": "UK",
        "program": "Java Web Developer ",
        "education": "Filosophy and French Bachelor Degree",
        "degree": "Humanities",
        "related": "no",
        "professional": "Restaurant Manager and English Teacher ",
        "workType": "More than 5 years",
        "workTime": "Online course ",
        "previousExt": "-"
    },
    {
        "name": "Carles Mora",
        "dob": "06/03/1972",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Economics Degree ",
        "degree": "Business",
        "related": "no",
        "professional": "Departments Coordinator ",
        "workType": "More than 2 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Carlos del Pozo",
        "dob": "24/07/1988",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Business Degree ",
        "degree": "Business",
        "related": "no",
        "professional": "Business Managment ",
        "workType": "More than 5 years",
        "workTime": "Course ",
        "previousExt": "Google Adwords Fundamental"
    },
    {
        "name": "Daniel Herrero Ortiz",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Aerospace Engineering and Business Managment Degree",
        "degree": "Technical",
        "related": "no",
        "professional": "Assistant Manager ",
        "workType": "More than 2 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Eduard Batlle ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer",
        "education": "Auto Mechanic Diploma ",
        "degree": "None",
        "related": "no",
        "professional": "Logistic Assistant ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Eduard Clarà ",
        "dob": "29",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Human Nutrition and Dietetics Degree",
        "degree": "Sciences",
        "related": "no",
        "professional": "Administrative Assistant ",
        "workType": "More than 5 years",
        "workTime": "No"
    },
    {
        "name": "Eduardo Alberto Cabrera Salvaña",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Technical Engineering Computer Systems ",
        "degree": "Technical",
        "related": "yes",
        "professional": "Computer System Technician ",
        "workType": "More than 5 years",
        "workTime": " - ",
        "previousExt": " - "
    },
    {
        "name": "Eduardo Pastor",
        "dob": "01/02/1992",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Business and International Marketing Degree",
        "degree": "Business",
        "related": "no",
        "professional": "Digital Business Managment and Sales ",
        "workType": "Less than 2 years",
        "workTime": "No",
        "previousExt": "-"
    },
    {
        "name": "Eduardo Torres ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Business Managment and Administration ",
        "degree": "Business",
        "related": "no",
        "professional": "Accountant and controller ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Egle Mekaite ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Master's Degree in Law",
        "degree": "Law",
        "related": "no",
        "professional": "Lawyer/ Freelance translator",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Ernesto Olivier ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Informatic Engineer and telecomunications ",
        "degree": "Technical",
        "related": "no",
        "professional": "Project manager IT",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Eva Espejo Palomo",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "English Philology Degree",
        "degree": "Humanities",
        "related": "no",
        "professional": "Branch Manager ",
        "workType": "More than 5 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Francesc Altes ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Mechanical Engineering Degree",
        "degree": "Technical",
        "related": "no",
        "professional": "Project Managment ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Francesc Gimenez Gil",
        "dob": "",
        "country": "Spain ",
        "program": "Java Web Developer ",
        "education": "Superior Degree in Arts and Design ",
        "degree": "Humanities",
        "related": "no",
        "professional": "Graphic Web Design ",
        "workType": "More than 5 years",
        "workTime": "Course (200h)",
        "previousExt": "HTLM/ CSS/ and Javascript for Web Developers"
    },
    {
        "name": "Gabriel Ristow ",
        "dob": "",
        "country": "",
        "program": "Data Analystics ",
        "education": "Business Administration/MBA",
        "degree": "Business",
        "related": "no",
        "professional": "Market analyst in Market Research ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Gerard de Haro Ramirez",
        "dob": "01/11/1994",
        "country": "Spain ",
        "program": "Java Web Developer ",
        "education": "Audiovision Communication ",
        "degree": "Humanities",
        "related": "no",
        "professional": "Video Edit and Maker ",
        "workType": "More than 2 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Gerard Pagans",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Architecture Degree and Computer Engineering ",
        "degree": "Technical",
        "related": "no",
        "professional": "Handball Coach ",
        "workType": "More than 5 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Gustavo Sanchez",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Superior Course Mechnical Projects Development",
        "degree": "None",
        "related": "no",
        "professional": "Draftsman",
        "workType": "More than 5 years",
        "workTime": "Courses ",
        "previousExt": "AutoDesk Inventor CAD 3D( 32h) and SolidWorks CAD 3D (60h)"
    },
    {
        "name": "Gustavo Sueza",
        "dob": "",
        "country": "Brasil ",
        "program": "Data Analystics ",
        "education": "Hospitality Bachelor and Marketing Master Degree",
        "degree": "Business",
        "related": "no",
        "professional": "Business Developer ",
        "workType": "More than 5 years",
        "workTime": "No",
        "previousExt": "-"
    },
    {
        "name": "Pedro Serrano",
        "dob": "",
        "country": "",
        "program": "Front-end",
        "education": "Cycle of Informatic Systems ",
        "degree": "",
        "related": "",
        "professional": "",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Montse Coriba ",
        "dob": "",
        "country": "",
        "program": "Front-end"
    },
    {
        "name": "David Cardenete",
        "dob": "",
        "country": "",
        "program": "Front-end"
    },
    {
        "name": "Alejandro Gomez Pulgarín",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Cristina Verdi Tobon",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "David Romero Araez",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Edgar Blanch Hernandez",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Jordi Vilagut Tressera",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Juan Jose Miron Molina",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Kristina Janovcikova",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Louis Van Noorden",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Marcel Tauber Cubero",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Pedro Alegre",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Raul Martinez Perez",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Rubén Peregrina",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Xavier Launes Garcia",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Albert Maurici Vidal",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Antoni Mateu Aguiló",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Guillem Vidiella",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Luca Bellarosa",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Marc Roca",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Meritxell Gramunt Oriol",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Raquel Redo Pardo",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Ruben Guerrero Ramierez",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Toni Diaz Rey",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Toni Requena Gascón",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Ignacio Perez ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "BSc Geology ",
        "degree": "Humanities",
        "related": "no",
        "professional": "- ",
        "workType": "",
        "workTime": "1 year ",
        "previousExt": "Data Analyst "
    },
    {
        "name": "Ignacio Soteras",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Bsc in Physics and  Ph.D Computatorial Chemistry ",
        "degree": "Sciences",
        "related": "no",
        "professional": "MSc in Big Data ",
        "workType": "More than 2 years",
        "workTime": "Online Courses ",
        "previousExt": "Machine Learning"
    },
    {
        "name": "Ines Neto",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Bachelor's Degree in Business Administration and Managment ",
        "degree": "Business",
        "related": "no",
        "professional": "Account and Project Managment ",
        "workType": "More than 2 years",
        "workTime": "No ",
        "previousExt": "- "
    },
    {
        "name": "Jaume Perelló",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Information technology training and dissemination programming(IT)",
        "degree": "",
        "related": "no",
        "professional": "Accounting",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Javier Venegas ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Technical Computer Systems Engineering Degree",
        "degree": "Technical",
        "related": "yes",
        "professional": "SQA Engineer",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Jesus Perelló",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Engineering Degree",
        "degree": "Technical",
        "related": "no",
        "professional": "Project Engineer and Director  ",
        "workType": "More than 5 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Joan Domenech Ivars",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Technician in Administration and Finance ",
        "degree": "Business",
        "related": "no",
        "professional": "Insurance Agent ",
        "workType": "More than 5 years",
        "workTime": "No",
        "previousExt": ""
    },
    {
        "name": "Lluis Casajuana Alpens",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Joan Manuel López ",
        "dob": "",
        "country": "",
        "program": "Data Analystics ",
        "education": "MSc Telecommunications ",
        "degree": "Technical",
        "related": "no",
        "professional": "Analyst Programmer ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Joe Difrancesco",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "MBA Entrepreneurship",
        "degree": "Business",
        "related": "no",
        "professional": "Assistant Planner and Contracting Lead",
        "workType": "More than 5 years",
        "workTime": "Le Wagoon student ",
        "previousExt": "4 meses "
    },
    {
        "name": "Jordi Vidal ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Not previously formation",
        "degree": "None",
        "related": "no",
        "professional": "Technician and sales ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Jörg Schönau*",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "BA in Technical Translating ",
        "degree": "Humanities",
        "related": "no",
        "professional": "Data Analyst ",
        "workType": "More than 5 years",
        "workTime": "No",
        "previousExt": "-"
    },
    {
        "name": "Juan Garriga Cots",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Law Degree and M in Business Consulting ",
        "degree": "Business",
        "related": "no",
        "professional": "Legal Adviser and Team Coordinator ",
        "workType": "More than 5 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Juan Pablo Vasini",
        "dob": "14/12/1995",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Business Administration Degree (2 years and a half) ",
        "degree": "Business",
        "related": "no",
        "professional": "Administrative and Technician Assistant",
        "workType": "More than 2 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Julie Pasechnik",
        "dob": "01/05/1987",
        "country": "Croatia",
        "program": "Data Analystics ",
        "education": "International Business Managment",
        "degree": "Business",
        "related": "no",
        "professional": "Coordinator and Account Manager ",
        "workType": "More than 5 years",
        "workTime": "No",
        "previousExt": ""
    },
    {
        "name": "Julio Climent ",
        "dob": "",
        "country": "",
        "program": "Data Analystics ",
        "education": "Degree in Business Administration and Managment/ M Investment Strategies and Financial Risk Managment  ",
        "degree": "Business",
        "related": "no",
        "professional": "Maintenance and Industrial Controller ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Karin Kromeke ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Bachelor in Business Administration/ Hospitality diploma ",
        "degree": "Business",
        "related": "no",
        "professional": "Production Coordinator ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Konstantina Tsagkari",
        "dob": "",
        "country": "Greece",
        "program": "Java Web Developer ",
        "education": "BSc in Maritime Economics",
        "degree": "Business",
        "related": "no",
        "professional": "Coordinator Department ",
        "workType": "More than 2 years",
        "workTime": "No ",
        "previousExt": "- "
    },
    {
        "name": "Lucian Maris",
        "dob": "10/10/1990",
        "country": "Spain/ Romania ",
        "program": "Java Web Developer ",
        "education": "Economic Sciences and Business Managment Degree",
        "degree": "Business",
        "related": "no",
        "professional": "Manager/Waiter/Bartender",
        "workType": "More than 5 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Albert Vicente Sanchez ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "",
        "degree": "",
        "related": "",
        "professional": "",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Bruno Ortiz ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Madoka  Uchida",
        "dob": "",
        "country": "Ireland ",
        "program": "Data Analystics ",
        "education": "Bachelor's Degree in Global Political Science and Economics ",
        "degree": "Business",
        "related": "no",
        "professional": "Commercial ",
        "workType": "More than 5 years",
        "workTime": "No",
        "previousExt": "-"
    },
    {
        "name": "Marc Vea ",
        "dob": "",
        "country": "",
        "program": "Data Analystics ",
        "education": "Psycology Degree",
        "degree": "Humanities",
        "related": "no",
        "professional": "Psicology",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Marcelo Garcia",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "International Relations ",
        "degree": "Business",
        "related": "no",
        "professional": "Business Developer and Customer service ",
        "workType": "More than 5 years",
        "workTime": "No ",
        "previousExt": "-"
    },
    {
        "name": "Marialena Kon",
        "dob": "",
        "country": "Greece",
        "program": "Java Web Developer ",
        "education": "Bachelor Degree in Architecture and Master in Architecture, Energy and Environment",
        "degree": "Business",
        "related": "no",
        "professional": "Support Agent ",
        "workType": "More than 5 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Alberto Espinosa ",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Marta Lopez",
        "dob": "21/11/1991",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Graphic Design ",
        "degree": "Humanities",
        "related": "no",
        "professional": "Digital Marketing and Social Media Community Manager ",
        "workType": "More than 5 years",
        "workTime": "No ",
        "previousExt": "- "
    },
    {
        "name": "Mauro Flores",
        "dob": "14/08/1990",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Bachelor's Degree in Intermedia/Multimedia ",
        "degree": "Humanities",
        "related": "no",
        "professional": "Content Writer and Translator ",
        "workType": "More than 2 years",
        "workTime": "No ",
        "previousExt": "-"
    },
    {
        "name": "Micaela Lescano",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Physiotherapy Degree",
        "degree": "Sciences",
        "related": "no",
        "professional": "Customer Service ",
        "workType": "More than 2 years",
        "workTime": "No ",
        "previousExt": "-"
    },
    {
        "name": "Miquel Costa",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Video Games Animation and Interactive Environments Degree (2 years)",
        "degree": "Technical",
        "related": "yes",
        "professional": "Graphic Design ",
        "workType": "Less than 2 years",
        "workTime": "No",
        "previousExt": ""
    },
    {
        "name": "Miquel Zelich",
        "dob": "",
        "country": "",
        "program": "Data Analystics ",
        "education": "Economics Degree/ M Green Managment Energy and CSR",
        "degree": "Business",
        "related": "no",
        "professional": "Electric Market Analyst",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Mohammed Najjar",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Communication Engineer ",
        "degree": "Technical",
        "related": "yes",
        "professional": "Customer Support Engineer",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Maruti ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Mykyta Andreiev",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Business Administration and International Affairs ",
        "degree": "Business",
        "related": "no",
        "professional": "Research Assistant ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Pol Benedito Momplet",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "No tiene info en LinkedIn"
    },
    {
        "name": "Mykyta Gnilobok",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "International relations Bachelor/ MBA ",
        "degree": "Business",
        "related": "no",
        "professional": "Sales Intern",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Jorge Luis Castillo Valderrama",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Neus Montserrat ",
        "dob": "",
        "country": "",
        "program": "Data Analystics ",
        "education": "Market Research ",
        "degree": "Business",
        "related": "no",
        "professional": "Marketing project Managment and Data Analyst ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Oriol Ballesteros ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Criminology's Degree ",
        "degree": "Humanities",
        "related": "no",
        "professional": "Customer services ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Amara Diallo",
        "dob": "",
        "country": "SouthAfrica",
        "program": "Data Analystics ",
        "education": "Bachelor of Science in Computer Information Technology ",
        "degree": "",
        "related": "",
        "professional": "",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Patricia Sánchez",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "BSc, International Business & Economics",
        "degree": "Business",
        "related": "no",
        "professional": "Financial Risk Management",
        "workType": "More than 2 years",
        "workTime": "No ",
        "previousExt": "-"
    },
    {
        "name": "Pau Andres Flores Cerda",
        "dob": "18/10/1986",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Physics Degree  ans M in Nanosciences and Nanotechnology ",
        "degree": "Sciences",
        "related": "no",
        "professional": "Consultant CRM and programmer SAP ",
        "workType": "More than 2 years",
        "workTime": "Course ",
        "previousExt": "R Programming and Data Scientit's Toolbox"
    },
    {
        "name": "Paula Castañer ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Digital Communication ",
        "degree": "Business",
        "related": "no",
        "professional": "Not previous work experince ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Pedro Zamora",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Technical Engineering in Computer Systems Degree",
        "degree": "Technical",
        "related": "no",
        "professional": "Host Programmer ",
        "workType": "More than 5 years",
        "workTime": "No",
        "previousExt": "-"
    },
    {
        "name": "Renata Montenegro ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Economics Degree/ M. Finance and Accounting",
        "degree": "Business",
        "related": "no",
        "professional": "Market development & financial analysis ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Ricard Esteve ",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Tourism Diploma and Hotel Managment ",
        "degree": "Business",
        "related": "no",
        "professional": "Department coordinator and Customer Support ",
        "workType": "More than 5 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Ricard Sánchez",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Business Managment Degree",
        "degree": "Business",
        "related": "no",
        "professional": "Consultant and Customer Service ",
        "workType": "More than 2 years",
        "workTime": "No ",
        "previousExt": "- "
    },
    {
        "name": "Roberto Jose Farina Medina",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Electrical, Electronics and Communication Engineering Bachelor Degree",
        "degree": "Technical",
        "related": "no",
        "professional": "Support Engineer",
        "workType": "More than 2 years",
        "workTime": "No ",
        "previousExt": "- "
    },
    {
        "name": "Roc Fàbregas",
        "dob": "21/06/1991",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Bachelor's Degree in Managment and Marketing",
        "degree": "Business",
        "related": "no",
        "professional": "Assistant Brand Planner ",
        "workType": "More than 2 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Roger Moga",
        "dob": "29.11.1983",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Industrial Design ",
        "degree": "Technical",
        "related": "no",
        "professional": "IT Developer and Founder at AP Group ",
        "workType": "More than 5 years",
        "workTime": "No ",
        "previousExt": "-"
    },
    {
        "name": "Rubén Martínez",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Industrial Engineer Degree ",
        "degree": "Technical",
        "related": "no",
        "professional": "Co-Funder Evernight App and Lean Manufacturing Engineer",
        "workType": "More than 2 years",
        "workTime": "Courses ",
        "previousExt": "Introduction to Business Intelligence and Big Data, and Advances Analysis of information with Excel "
    },
    {
        "name": "Ruben Tugnolo",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "BSc Science in Rdiologic Technologies ",
        "degree": "Sciences",
        "related": "no",
        "professional": "CT Technician ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Ruth Gascón ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Audiovisual communication Degree ",
        "degree": "Humanities",
        "related": "no",
        "professional": "Project Manager ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Sara Marín-López",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Licenciate in Psychology and PHD in Social Psychology",
        "degree": "Humanities",
        "related": "no",
        "professional": "Psychologist and Teaching",
        "workType": "More than 2 years",
        "workTime": "No ",
        "previousExt": "-"
    },
    {
        "name": "Sasha Riberas",
        "dob": "",
        "country": "",
        "program": "Front-end",
        "education": "Not previously formation",
        "degree": "None",
        "related": "no",
        "professional": "Rowing Monitor ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Sooraj Dondaparty",
        "dob": "24/08/1987",
        "country": "India",
        "program": "Java Web Developer ",
        "education": "Bachelor's in Science and Post graduate in Business Managment ",
        "degree": "Business",
        "related": "no",
        "professional": "HHRR Executive and Business Assistant",
        "workType": "More than 5 years",
        "workTime": "No",
        "previousExt": ""
    },
    {
        "name": "Sophie Willis",
        "dob": "20",
        "country": "UK ",
        "program": "Java Web Developer ",
        "education": "Licenciature in Design ",
        "degree": "Humanities",
        "related": "no",
        "professional": "Sales Assistant and Team Supervisor ",
        "workType": "",
        "workTime": "Part-time Online course ",
        "previousExt": "UDEMY"
    },
    {
        "name": "Stephanie Helle",
        "dob": "",
        "country": "Germany ",
        "program": "Java Web Developer ",
        "education": "Bachelor of Arts, Sociology, Cum Laude",
        "degree": "Humanities",
        "related": "no",
        "professional": "Project Manager and Data Base Coordinator",
        "workType": "More than 2 years",
        "workTime": "No ",
        "previousExt": "-"
    },
    {
        "name": "Tatiana Morera",
        "dob": "27/03/1992",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "CFS in Graphic Design and Master’s degree in Design & Web\r\nDevelopment",
        "degree": "Technical",
        "related": "yes",
        "professional": "Frontend ",
        "workType": "More than 2 years",
        "workTime": "No ",
        "previousExt": "- "
    },
    {
        "name": "Teresa Juan",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Biology Degree",
        "degree": "Sciences",
        "related": "no",
        "professional": "R+D Technician",
        "workType": "More than 5 years",
        "workTime": "No ",
        "previousExt": "-"
    },
    {
        "name": "Valerii Radko",
        "dob": "",
        "country": "Ukraine",
        "program": "Java Web Developer ",
        "education": "Bachelor’s Degree in Physics and Master’s degree in radiophysics and electronics",
        "degree": "Sciences",
        "related": "no",
        "professional": "Marketing Manager ",
        "workType": "More than 5 years",
        "workTime": "No ",
        "previousExt": "- "
    },
    {
        "name": "Berenguer Pou",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "CFGS, AV and Lighting Design ",
        "degree": "",
        "related": "",
        "professional": "",
        "workType": "",
        "workTime": "No ",
        "previousExt": "- "
    },
    {
        "name": "Vera Giulia Sala",
        "dob": "",
        "country": "Spain",
        "program": "Data Analystics ",
        "education": "Physics Degree, Master and PhD ",
        "degree": "Sciences",
        "related": "no",
        "professional": "Research Activity in Physics ",
        "workType": "More than 5 years",
        "workTime": "No",
        "previousExt": "-"
    },
    {
        "name": "Vicent Clapés Prats",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Criminology and Private Investigation Degree (3 years)",
        "degree": "Humanities",
        "related": "no",
        "professional": "Administrative coordinator ",
        "workType": "More than 5 years",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Victor Carpio ",
        "dob": "",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Computer Systems Administration",
        "degree": "Technical",
        "related": "no",
        "professional": "Co-worker and Supervisor ",
        "workType": "More than 2 years",
        "workTime": "No"
    },
    {
        "name": "Victor Demoragas",
        "dob": "21/06/1989",
        "country": "Spain",
        "program": "Java Web Developer ",
        "education": "Business Degree ",
        "degree": "Business",
        "related": "no",
        "professional": "Digital Marketing",
        "workType": "Less than 2 years",
        "workTime": "Freelance ",
        "previousExt": "Social Network Creator "
    },
    {
        "name": "Victor Greco",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Marketing Certification",
        "degree": "Business",
        "related": "no",
        "professional": "Marketing",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Violeta Mezeklieva*",
        "dob": "",
        "country": "Netherlands ",
        "program": "Data Analystics ",
        "education": "Political Sciences and Environmental Policy Degree",
        "degree": "Business",
        "related": "no",
        "professional": "Festival Coordinator",
        "workType": "More than 2 years",
        "workTime": "No",
        "previousExt": "-"
    },
    {
        "name": "Virginia Gonzales",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Degree in Clinical Laboratory / Accounting Administrative",
        "degree": "Sciences",
        "related": "no",
        "professional": "Laboratory Analysis",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Xavier Mendez Garcia ",
        "dob": "",
        "country": "",
        "program": "Front-end",
        "education": "Marketing and Communication Managment Degree",
        "degree": "Business",
        "related": "no",
        "professional": "Grafic Design ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Yash Saha",
        "dob": "",
        "country": "India",
        "program": "Data Analystics ",
        "education": "Bachelor in Engineering in Computer Science and Engineering ",
        "degree": "Technical",
        "related": "yes",
        "professional": "Intern in Banking in IT",
        "workType": "Less than 2 years",
        "workTime": "Courses ",
        "previousExt": "Core Java at CDAC, Python's Beginners at DataQuest.com and Intro to Python's for Data Science at Bootcamp.com"
    },
    {
        "name": "Zvonimir Planinic ",
        "dob": "",
        "country": "",
        "program": "Java Web Developer ",
        "education": "Degree in Trafgic Sciences/ M Intelligence Transportation Systems ",
        "degree": "Technical",
        "related": "no",
        "professional": "Traffic Engineer ",
        "workType": "",
        "workTime": "",
        "previousExt": ""
    },
    {
        "name": "Jaume Bonet",
        "dob": "",
        "country": "",
        "program": "Java Web Developer "
    },
    {
        "name": "Elisabet Gimeno",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Bernat Saperas",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Jaume Soler",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "José Antonio Medina",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Alexander Winkler",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    },
    {
        "name": "Jean-Yves Devloo",
        "dob": "",
        "country": "",
        "program": "Data Analystics "
    }
]